### ISSUE TITLE
Safari doesn't show a search input

### ISSUE THREAD

**Issue by djadomi** [composablehorizons/composeicons#12] opened 2024-12-13 19:22 UTC
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/8b810234-c482-4b7d-bc6e-cfcf7048180d" />

Safari Version 18.1.1 (20619.2.8.11.12)

(and don't get me started on Safari dev tools to diagnose it…!)

**Comment by alexstyl** [comment] 2024-12-14 05:44
Cannot reproduce it on Safari.

Does it work without extensions? Give it a go with incognito mode.

Does it work on other browsers on your computer?

**Comment by djadomi** [comment] 2024-12-14 11:03
You're correct about Extensions: AdBlock seems not to like it, specifically AdBlock Engine 2.1.8…

Here's a screenshot of it in a Private Window with devtools open on it (AdBlock still enabled):

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/2d0cb1d7-f571-4e16-8ae9-205c41d66ad6" />

I don't see anything in that simple html that would trigger AdBlock. Brave and DuckDuckGo don't mind it and AdBlock in both Chrome Canary and Firefox doesn't hide it either.

In fact, I just checked a different Mac and I can see it with Safari + AdBlock - the only difference between them is CPU: Intel iMac gets it and M4 MacBook has it blocked, but I can't imagine that comes into the equation. The iMac is still macOS 15.1.1 and the MacBook is 15.2 but I reported this before I updated the MBP.

Edge case, but confusing if you use whatever combination of Mac + Safari causes this and don't already know there's supposed to be a search input there.

(Thanks again for the very useful resource.)

**Comment by alexstyl** [comment] 2024-12-14 11:13
I am not familiar with adblock so I cannot help much. is it possible that you might have accidentally set a rule to hide the search bar?

I know that some ad blockers support the hiding of some elements on the screen like popups etc.

Either way, closing this as it seems unrelated to the site.

**Closed by alexstyl** 2024-12-14 11:13 UTC
Labels: more info required

**Comment by djadomi** [comment] 2024-12-14 11:19
Nothing special about the AdBlock setup: just installed the extension and left it as-is.

The only thing I'd do to be an _absolute_ completist is check if `MutationObserver` could catch that the input's parent element has been hidden, and show a message if so. As I say, I'd classify that as _extreme_ edge-case handling!

Cheers
